"""Remove no null conntraint from file hash in filemetadata

Revision ID: 71c1bab20f58
Revises: d666daa14c00
Create Date: 2026-05-31 20:31:28.803239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '71c1bab20f58'
down_revision: Union[str, Sequence[str], None] = 'd666daa14c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_metadata', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_metadata', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    
    
