"""add file details to job

Revision ID: ad4980332d7b
Revises: 71c1bab20f58
Create Date: 2026-06-04 19:51:31.063545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4980332d7b'
down_revision: Union[str, Sequence[str], None] = '71c1bab20f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fetched_files', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('processed_files', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('stored_files', sa.Integer(), nullable=True))
    op.drop_column('jobs', 'done_files')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('done_files', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'stored_files')
    op.drop_column('jobs', 'processed_files')
    op.drop_column('jobs', 'fetched_files')
    # ### end Alembic commands ###
