"""add total_files done_files to jobs

Revision ID: b4b4d420b1dd
Revises: c4e0a842b507
Create Date: 2026-05-29 13:55:29.425894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b4d420b1dd'
down_revision: Union[str, Sequence[str], None] = 'c4e0a842b507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('total_files', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('done_files', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'done_files')
    op.drop_column('jobs', 'total_files')
    # ### end Alembic commands ###
