"""change default value of ingesting queue

Revision ID: 8daccf9b1a3b
Revises: f7d6c8821073
Create Date: 2026-03-20 23:08:22.312302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daccf9b1a3b'
down_revision: Union[str, Sequence[str], None] = 'f7d6c8821073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
