name: CI/CD Pipeline - GitLense

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
        branches: [main]
    workflow_dispatch:
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}

            - name: Login to ACR
              run:  |
                #Login to ACR
                az acr login --name $${{secrets.ACR_REGISTRY_NAME}}



            - name: Build and Push image
              run: |
                
                IMAGE_TAG=$${{secrets.ACR_LOGIN_SERVER}}/gitlense:v1
                docker build -t $IMAGE_TAG
                docker push $IMAGE_TAG
            
            - name: SSH and Update VM
              uses: appleboy/ssh-action@v1.0.3
              with: 
                host: ${{secrets.VM_IP}}
                username: ${{secrets.VM_USER}}
                key: ${{secrets.SSH_PRIVATE_KEY}}
                script: |
                    #Navigate to project folder
                    cd gitlense

                    echo "${{secrets.AZURE_CLIENT_SECRET}}" | docker login $${{secrets.ACR_LOGIN_SERVER}} \
                        -u $${{secrets.AZURE_CLIENT_ID}} \
                        --password-stdin
                    
                    docker compose pull
                    docker compose up -d

                    docker image prune -f





